# Generated by Django 5.2.15 on 2026-08-05 10:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DuelMatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('score_a', models.IntegerField(default=0)),
                ('score_b', models.IntegerField(default=0)),
                ('elo_delta_a', models.IntegerField(default=0)),
                ('elo_delta_b', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('player_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_host', to=settings.AUTH_USER_MODEL)),
                ('player_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_guest', to=settings.AUTH_USER_MODEL)),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_duels', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'duel_matches',
                'ordering': ['-created_at'],
            },
        ),
    ]
