# Generated by Django 5.2.15 on 2026-06-22 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved / Published'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
