# Generated by Django 5.2.15 on 2026-06-22 17:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems_app', '0002_problem_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProblemStats',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('attempted', 'Attempted'), ('solved', 'Solved')], default='attempted', max_length=20)),
                ('attempts_count', models.IntegerField(default=0)),
                ('last_attempted_at', models.DateTimeField(auto_now=True)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_stats', to='problems_app.problem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problem_stats', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_problem_stats',
                'unique_together': {('user', 'problem')},
            },
        ),
    ]
