# Generated by Django 5.2.15 on 2026-07-10 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems_app', '0003_userproblemstats'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='templates',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
