# Generated by Django 5.2.15 on 2026-08-03 17:34

from django.db import migrations, models


def populate_serial_numbers(apps, schema_editor):
    Problem = apps.get_model('problems_app', 'Problem')
    problems = Problem.objects.all().order_by('created_at', 'title')
    for index, problem in enumerate(problems, start=1):
        problem.serial_no = index
        problem.save()


class Migration(migrations.Migration):

    dependencies = [
        ('problems_app', '0004_problem_templates'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='serial_no',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.RunPython(populate_serial_numbers, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='problem',
            name='serial_no',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
    ]

