# Generated by Django 5.2.15 on 2026-08-07 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("problems_app", "0005_changerequest"),
        ("problems_app", "0005_problem_serial_no"),
    ]

    operations = []

