# Generated by Django 5.2.15 on 2026-08-07 18:50

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("problems_app", "0006_merge_0005_changerequest_0005_problem_serial_no"),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyBug",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("category", models.CharField(max_length=30)),
                ("description", models.TextField()),
                ("starter_codes", models.JSONField(default=dict)),
                ("test_cases_json", models.JSONField(default=list)),
                ("examples", models.JSONField(default=list)),
                ("sample_input", models.TextField()),
                ("expected_output", models.TextField()),
                ("line_budget", models.IntegerField(default=1)),
                ("xp_reward", models.IntegerField(default=100)),
                ("time_limit_ms", models.IntegerField(default=2000)),
                ("date", models.DateField(unique=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "daily_bugs",
                "ordering": ["-date"],
            },
        ),
    ]
