# Generated by Django 5.2.15 on 2026-08-06 05:07

import datetime
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems_app', '0006_merge_0005_changerequest_0005_problem_serial_no'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyBug',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('arrays', 'Arrays'), ('strings', 'Strings'), ('loops', 'Loops'), ('recursion', 'Recursion'), ('sorting', 'Sorting'), ('math', 'Math'), ('logic', 'Logic'), ('other', 'Other')], default='other', max_length=30)),
                ('description', models.TextField()),
                ('starter_codes', models.JSONField(default=dict, help_text='{"python": "def solve():\\n    pass", "javascript": "...", "cpp": "..."}')),
                ('test_cases_json', models.JSONField(blank=True, default=list)),
                ('examples', models.JSONField(blank=True, default=list)),
                ('sample_input', models.TextField(blank=True, default='')),
                ('expected_output', models.TextField(blank=True, default='')),
                ('line_budget', models.PositiveIntegerField(default=3, help_text='Max number of lines the user is allowed to modify.')),
                ('xp_reward', models.PositiveIntegerField(default=100)),
                ('time_limit_ms', models.IntegerField(default=2000)),
                ('date', models.DateField(default=datetime.date.today, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'daily_bugs',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='UserBugSolve',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('solved_at', models.DateTimeField(auto_now_add=True)),
                ('bug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solves', to='problems_app.dailybug')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bug_solves', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_bug_solves',
                'unique_together': {('user', 'bug')},
            },
        ),
    ]
