# Generated by Django 5.2.15 on 2026-06-22 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstats',
            name='role',
            field=models.CharField(choices=[('competitor', 'Competitor'), ('moderator', 'Moderator / Problem Setter'), ('superadmin', 'Superadmin')], default='competitor', max_length=20),
        ),
    ]
