# Generated by Django 5.2.15 on 2026-06-26 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0002_userstats_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userstats',
            old_name='elo_rating',
            new_name='contest_rating',
        ),
        migrations.AddField(
            model_name='userstats',
            name='duel_rating',
            field=models.IntegerField(default=1200),
        ),
    ]
