# Generated by Django 5.2.16 on 2026-08-05 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth_app", "0003_rename_elo_rating_userstats_contest_rating_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userstats",
            name="flag_reason",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="userstats",
            name="is_flagged",
            field=models.BooleanField(default=False),
        ),
    ]
