# Generated by Django 5.2.15 on 2026-08-06 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0004_userstats_flag_reason_userstats_is_flagged'),
        ('auth_app', '0005_delete_duelmatch'),
    ]

    operations = [
    ]
