# Generated by Django 5.2.15 on 2026-06-22 14:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('type', models.CharField(choices=[('public', 'Public'), ('private', 'Private'), ('classroom', 'Classroom')], default='public', max_length=20)),
                ('scoring_mode', models.CharField(choices=[('leetcode', 'LeetCode (Virtual Score)'), ('codeforces', 'Codeforces (Time-based Penalty)')], default='leetcode', max_length=20)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('access_code', models.CharField(blank=True, max_length=20, null=True)),
                ('is_rated', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_contests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'contests',
            },
        ),
        migrations.CreateModel(
            name='ContestParticipant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rank', models.IntegerField(blank=True, null=True)),
                ('total_score', models.IntegerField(default=0)),
                ('penalty_minutes', models.IntegerField(default=0)),
                ('elo_change', models.IntegerField(blank=True, null=True)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='contests_app.contest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contests_joined', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'contest_participants',
            },
        ),
        migrations.CreateModel(
            name='ContestProblem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('points', models.IntegerField(default=100)),
                ('order_index', models.IntegerField(default=0)),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contest_problems', to='contests_app.contest')),
            ],
            options={
                'db_table': 'contest_problems',
                'ordering': ['order_index'],
            },
        ),
    ]
