# Generated by Django 5.2.15 on 2026-06-22 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contests_app', '0001_initial'),
        ('problems_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contestproblem',
            name='problem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contest_problems', to='problems_app.problem'),
        ),
        migrations.AlterUniqueTogether(
            name='contestparticipant',
            unique_together={('contest', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='contestproblem',
            unique_together={('contest', 'problem')},
        ),
    ]
