# Generated by Django 5.2.15 on 2026-06-22 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests_app', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='eligible_class_tier',
            field=models.CharField(choices=[('class_1', 'Class 1 (Advanced: ELO 1800+)'), ('class_2', 'Class 2 (Intermediate: ELO 1400-1799)'), ('class_3', 'Class 3 (Beginner: ELO < 1400)'), ('all', 'All Tiers / Open')], default='all', max_length=20),
        ),
        migrations.AddField(
            model_name='contest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved / Published'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
