# Generated by Django 5.2.15 on 2026-06-22 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contests_app', '0003_contest_eligible_class_tier_contest_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contest',
            name='created_by',
        ),
    ]
