# Generated by Django 5.2.15 on 2026-07-06 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests_app', '0004_remove_contest_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='is_finalized',
            field=models.BooleanField(default=False),
        ),
    ]
